# -*- coding: utf-8 -*-
"""regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJz16G2hAhgPUwzJMKPMa6X1Q8CCrXzY
"""

#read the data
import numpy as np
X=[11,12,11,15,8,10,11,12,17,11]
Y=[25,33,22,41,18,28,32,24,53,26]
X=np.array(X)
Y=np.array(Y)

def calculate_mean(arr):
  arr_mean=np.mean(arr)
  return arr_mean

X_mean=calculate_mean(X)
Y_mean=calculate_mean(Y)
X_sub=X-X_mean
Y_sub=Y-Y_mean
print(X_sub)
print(Y_sub)

X_squared=X_sub*X_sub
XY=X_sub*Y_sub

covariance=np.sum(XY)
variance=np.sum(X_squared)
slope=covariance/variance
print("this is the slope:",round(slope,2))

#c=y-mx
intercept=Y_mean-(slope*X_mean)
print("this is the intercept:",round(intercept,2))

#regression equation
print(f"regression equation: y={round(slope,2)} * x + {round(intercept,2)}")

import matplotlib.pyplot as plt
plt.scatter(X,Y)
plt.plot(X,((slope*X)+intercept))
plt.show()

#using built in function
from sklearn.linear_model import LinearRegression
model=LinearRegression()
X_2d=[[11],[12],[11],[15],[8],[10],[11],[12],[17],[11]]
model.fit(X_2d,Y)
#slope
print("slope: ",model.coef_[0])
print("intercept:",model.intercept_)
print("measures of how well the model actually matches the real data: \n",round(model.score(X_2d,Y),2))

#error
#calulating SSE
Y_reg=[]
X=[11,12,11,15,8,10,11,12,17,11]
for i in X:
  Y_reg.append(3.74 * i + -13.93)
residual=Y-Y_reg
squared_res=np.square(residual)
sse=np.sum(squared_res)
print("this is the SSE:",round(sse,2))

#mse
mse= sse/len(X)
print("the mse is: ",round(mse,2))

#rmse
import math
print("this is the rmse: ",math.sqrt(round(mse,2)) )

x_input=float(input("enter inpt value: "))
reg=3.74 * (x_input) + -13.93
print(f"the predicted value is {round(reg,2)}")